development:
  adapter: mysql2
  database: expresso_rasante_development
  username: clients
  password: clients123
test:
  adapter: mysql2
  database: expresso_rasante_test
  username: clients
  password: clients123

production:
  adapter: mysql2
  database: expresso_rasante_production
  username: clients
  password: clients123